import {type Faction, FACTIONS} from "./faction";
import {type Color} from "./color";

export type Scoring = {
    faction: Faction;
    scores: Record<Color["color"], number>;
};

export const DEFAULT_SCORING: Scoring[] = [
    {
        faction: FACTIONS.ARBOREC,
        scores: {
            Red: 1,
            Orange: 2,
            Yellow: 6,
            Green: 10,
            Blue: 0,
            Purple: 1,
            Pink: 0,
            Black: 2,
        },
    },
    {
        faction: FACTIONS.ARGENT,
        scores: {
            Red: 2,
            Orange: 10,
            Yellow: 2,
            Green: 7,
            Blue: 2,
            Purple: 2,
            Pink: 0,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.BARONY,
        scores: {
            Red: 8,
            Orange: 2,
            Yellow: 0,
            Green: 1,
            Blue: 4,
            Purple: 0,
            Pink: 0,
            Black: 9,
        },
    },
    {
        faction: FACTIONS.SAAR,
        scores: {
            Red: 1,
            Orange: 9,
            Yellow: 8,
            Green: 1,
            Blue: 0,
            Purple: 1,
            Pink: 0,
            Black: 2,
        },
    },
    {
        faction: FACTIONS.MUAAT,
        scores: {
            Red: 8,
            Orange: 9,
            Yellow: 4,
            Green: 0,
            Blue: 0,
            Purple: 0,
            Pink: 0,
            Black: 4,
        },
    },
    {
        faction: FACTIONS.HACAN,
        scores: {
            Red: 4,
            Orange: 8,
            Yellow: 9,
            Green: 0,
            Blue: 0,
            Purple: 0,
            Pink: 0,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.EMPYREAN,
        scores: {
            Red: 7,
            Orange: 4,
            Yellow: 1,
            Green: 0,
            Blue: 2,
            Purple: 9,
            Pink: 3,
            Black: 5,
        },
    },
    {
        faction: FACTIONS.SOL,
        scores: {
            Red: 2,
            Orange: 0,
            Yellow: 8,
            Green: 2,
            Blue: 9,
            Purple: 0,
            Pink: 0,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.GHOSTS,
        scores: {
            Red: 0,
            Orange: 1,
            Yellow: 0,
            Green: 1,
            Blue: 10,
            Purple: 2,
            Pink: 1,
            Black: 7,
        },
    },
    {
        faction: FACTIONS.L1Z1X,
        scores: {
            Red: 8,
            Orange: 1,
            Yellow: 0,
            Green: 1,
            Blue: 9,
            Purple: 0,
            Pink: 0,
            Black: 8,
        },
    },
    {
        faction: FACTIONS.MAHACT,
        scores: {
            Red: 1,
            Orange: 0,
            Yellow: 10,
            Green: 0,
            Blue: 0,
            Purple: 7,
            Pink: 2,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.MENTAK,
        scores: {
            Red: 0,
            Orange: 9,
            Yellow: 9,
            Green: 0,
            Blue: 0,
            Purple: 4,
            Pink: 0,
            Black: 8,
        },
    },
    {
        faction: FACTIONS.NAALU,
        scores: {
            Red: 0,
            Orange: 9,
            Yellow: 9,
            Green: 8,
            Blue: 0,
            Purple: 1,
            Pink: 0,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.NAAZ_ROKHA,
        scores: {
            Red: 1,
            Orange: 0,
            Yellow: 7,
            Green: 10,
            Blue: 0,
            Purple: 1,
            Pink: 0,
            Black: 2,
        },
    },
    {
        faction: FACTIONS.NEKRO,
        scores: {
            Red: 10,
            Orange: 1,
            Yellow: 1,
            Green: 0,
            Blue: 1,
            Purple: 1,
            Pink: 0,
            Black: 4,
        },
    },
    {
        faction: FACTIONS.NOMAD,
        scores: {
            Red: 1,
            Orange: 1,
            Yellow: 2,
            Green: 1,
            Blue: 8,
            Purple: 8,
            Pink: 7,
            Black: 4,
        },
    },
    {
        faction: FACTIONS.SARDAKK,
        scores: {
            Red: 9,
            Orange: 0,
            Yellow: 2,
            Green: 4,
            Blue: 0,
            Purple: 0,
            Pink: 0,
            Black: 8,
        },
    },
    {
        faction: FACTIONS.TITANS,
        scores: {
            Red: 0,
            Orange: 0,
            Yellow: 1,
            Green: 1,
            Blue: 1,
            Purple: 4,
            Pink: 10,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.JOL_NAR,
        scores: {
            Red: 0,
            Orange: 0,
            Yellow: 1,
            Green: 2,
            Blue: 8,
            Purple: 9,
            Pink: 4,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.VUIL_RAITH,
        scores: {
            Red: 10,
            Orange: 6,
            Yellow: 1,
            Green: 0,
            Blue: 0,
            Purple: 0,
            Pink: 0,
            Black: 6,
        },
    },
    {
        faction: FACTIONS.WINNU,
        scores: {
            Red: 6,
            Orange: 8,
            Yellow: 8,
            Green: 2,
            Blue: 0,
            Purple: 9,
            Pink: 1,
            Black: 1,
        },
    },
    {
        faction: FACTIONS.XXCHA,
        scores: {
            Red: 0,
            Orange: 1,
            Yellow: 4,
            Green: 10,
            Blue: 6,
            Purple: 1,
            Pink: 0,
            Black: 2,
        },
    },
    {
        faction: FACTIONS.YIN,
        scores: {
            Red: 0,
            Orange: 1,
            Yellow: 7,
            Green: 0,
            Blue: 0,
            Purple: 8,
            Pink: 4,
            Black: 5,
        },
    },
    {
        faction: FACTIONS.YSSARIL,
        scores: {
            Red: 7,
            Orange: 1,
            Yellow: 8,
            Green: 9,
            Blue: 0,
            Purple: 2,
            Pink: 0,
            Black: 6,
        },
    },
];